# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Uniforge < Formula
  desc "CLI tool for Unity development"
  homepage "https://github.com/neptaco/uniforge"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/neptaco/UniForge/releases/download/v0.4.0/UniForge_darwin_amd64.tar.gz"
      sha256 "11cd649dba7fbe3319fac11a0164c52a0cb737aa2dd44e0e0760247b6253def0"

      def install
        bin.install "uniforge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/neptaco/UniForge/releases/download/v0.4.0/UniForge_darwin_arm64.tar.gz"
      sha256 "2a4835982f356c8c64bc1aa6146e992fe0c120fd60eb8a7ca5163ccfd4226801"

      def install
        bin.install "uniforge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/neptaco/UniForge/releases/download/v0.4.0/UniForge_linux_amd64.tar.gz"
      sha256 "42caed544dff5adde161b0f3b2e7485eee51fb38c49b8c2ffb21ac90bfe24095"
      def install
        bin.install "uniforge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/neptaco/UniForge/releases/download/v0.4.0/UniForge_linux_arm64.tar.gz"
      sha256 "a118db031e140e2ad8b4fd72cf6ee566a15cdbf6602381c8e3da698a998f6515"
      def install
        bin.install "uniforge"
      end
    end
  end

  test do
    system "#{bin}/uniforge", "--version"
  end
end
