# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Uniforge < Formula
  desc "CLI tool for Unity development"
  homepage "https://github.com/neptaco/uniforge"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/neptaco/UniForge/releases/download/v0.3.0/UniForge_darwin_amd64.tar.gz"
      sha256 "2092547b6f5e7f83ad42bc1b9f459b10542330c8de38f0884bd8e6ce916091b6"

      def install
        bin.install "uniforge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/neptaco/UniForge/releases/download/v0.3.0/UniForge_darwin_arm64.tar.gz"
      sha256 "30fe740d72d9556e074159ef138eacf62f38edc49fd8c1b4b5f1f274851ef964"

      def install
        bin.install "uniforge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/neptaco/UniForge/releases/download/v0.3.0/UniForge_linux_amd64.tar.gz"
      sha256 "8ad97b4d6daea5352ee4ec1aaaeb97082a837cdd3bea368bfa7877d07a262f8b"
      def install
        bin.install "uniforge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/neptaco/UniForge/releases/download/v0.3.0/UniForge_linux_arm64.tar.gz"
      sha256 "66483ceeb674a66516d07d5116a1d412b5e957f487aad8a2fabc681fecff075f"
      def install
        bin.install "uniforge"
      end
    end
  end

  test do
    system "#{bin}/uniforge", "--version"
  end
end
