name: Update Formula

on:
  repository_dispatch:
    types: [update-formula]

permissions:
  contents: write

jobs:
  update-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Update Formula
        env:
          FORMULA_NAME: ${{ github.event.client_payload.formula }}
          VERSION: ${{ github.event.client_payload.version }}
        run: |
          echo "Updating formula: $FORMULA_NAME to version: $VERSION"
          
          # Remove 'v' prefix if present
          VERSION_NUM="${VERSION#v}"
          
          # Download and calculate SHA256 for each platform
          
          # macOS ARM64
          URL="https://github.com/neptaco/${FORMULA_NAME}/releases/download/${VERSION}/${FORMULA_NAME}-${VERSION}-aarch64-apple-darwin.tar.gz"
          SHA_MACOS_ARM64=$(curl -sL "${URL}.sha256" | awk '{print $1}')
          
          # macOS x86_64
          URL="https://github.com/neptaco/${FORMULA_NAME}/releases/download/${VERSION}/${FORMULA_NAME}-${VERSION}-x86_64-apple-darwin.tar.gz"
          SHA_MACOS_X64=$(curl -sL "${URL}.sha256" | awk '{print $1}')
          
          # Linux ARM64
          URL="https://github.com/neptaco/${FORMULA_NAME}/releases/download/${VERSION}/${FORMULA_NAME}-${VERSION}-aarch64-unknown-linux-gnu.tar.gz"
          SHA_LINUX_ARM64=$(curl -sL "${URL}.sha256" | awk '{print $1}')
          
          # Linux x86_64
          URL="https://github.com/neptaco/${FORMULA_NAME}/releases/download/${VERSION}/${FORMULA_NAME}-${VERSION}-x86_64-unknown-linux-gnu.tar.gz"
          SHA_LINUX_X64=$(curl -sL "${URL}.sha256" | awk '{print $1}')
          
          # Update the formula file
          FORMULA_FILE="Formula/${FORMULA_NAME}.rb"
          
          # Update version
          sed -i "s/version \".*\"/version \"${VERSION_NUM}\"/" "$FORMULA_FILE"
          
          # Update SHA256 hashes
          # macOS ARM64
          sed -i "/aarch64-apple-darwin/,/sha256/{s/sha256 \".*\"/sha256 \"${SHA_MACOS_ARM64}\"/}" "$FORMULA_FILE"
          
          # macOS x86_64
          sed -i "/x86_64-apple-darwin/,/sha256/{s/sha256 \".*\"/sha256 \"${SHA_MACOS_X64}\"/}" "$FORMULA_FILE"
          
          # Linux ARM64
          sed -i "/aarch64-unknown-linux-gnu/,/sha256/{s/sha256 \".*\"/sha256 \"${SHA_LINUX_ARM64}\"/}" "$FORMULA_FILE"
          
          # Linux x86_64
          sed -i "/x86_64-unknown-linux-gnu/,/sha256/{s/sha256 \".*\"/sha256 \"${SHA_LINUX_X64}\"/}" "$FORMULA_FILE"
          
          # Display changes
          echo "Formula updated:"
          git diff --color=always

      - name: Commit and Push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          FORMULA_NAME=${{ github.event.client_payload.formula }}
          VERSION=${{ github.event.client_payload.version }}
          
          git add Formula/${FORMULA_NAME}.rb
          
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update ${FORMULA_NAME} to ${VERSION}"
            git push
          fi