name: Update Formula

on:
  repository_dispatch:
    types: [update-formula]

permissions:
  contents: write

jobs:
  update-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Bump formula
        uses: dawidd6/action-homebrew-bump-formula@v4
        with:
          formula: ${{ github.event.client_payload.formula }}
          tag: ${{ github.event.client_payload.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          message: "Update ${{ github.event.client_payload.formula }} to ${{ github.event.client_payload.version }}"