name: Update Formula

on:
  repository_dispatch:
    types: [update-formula]
  workflow_dispatch:
    inputs:
      formula:
        description: 'Formula name to update'
        required: true
        default: 'mcproc'
      version:
        description: 'New version (e.g., v0.1.1)'
        required: true

permissions:
  contents: write

jobs:
  update-formula:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Update Formula
        env:
          FORMULA_NAME: ${{ github.event.client_payload.formula || github.event.inputs.formula }}
          VERSION: ${{ github.event.client_payload.version || github.event.inputs.version }}
        run: |
          set -e
          echo "Updating formula: $FORMULA_NAME to version: $VERSION"
          
          # Remove 'v' prefix if present
          VERSION_NUM="${VERSION#v}"
          echo "VERSION_NUM: $VERSION_NUM"
          
          # Download and calculate SHA256 for each platform
          echo "Downloading SHA256 checksums..."
          
          # macOS ARM64
          URL="https://github.com/neptaco/${FORMULA_NAME}/releases/download/${VERSION}/${FORMULA_NAME}-${VERSION_NUM}-aarch64-apple-darwin.tar.gz"
          echo "Fetching SHA256 for macOS ARM64 from: ${URL}.sha256"
          SHA_MACOS_ARM64=$(curl -sL "${URL}.sha256" | awk '{print $1}')
          echo "SHA_MACOS_ARM64: ${SHA_MACOS_ARM64}"
          
          # macOS x86_64
          URL="https://github.com/neptaco/${FORMULA_NAME}/releases/download/${VERSION}/${FORMULA_NAME}-${VERSION_NUM}-x86_64-apple-darwin.tar.gz"
          echo "Fetching SHA256 for macOS x86_64 from: ${URL}.sha256"
          SHA_MACOS_X64=$(curl -sL "${URL}.sha256" | awk '{print $1}')
          echo "SHA_MACOS_X64: ${SHA_MACOS_X64}"
          
          # Linux ARM64
          URL="https://github.com/neptaco/${FORMULA_NAME}/releases/download/${VERSION}/${FORMULA_NAME}-${VERSION_NUM}-aarch64-unknown-linux-gnu.tar.gz"
          echo "Fetching SHA256 for Linux ARM64 from: ${URL}.sha256"
          SHA_LINUX_ARM64=$(curl -sL "${URL}.sha256" | awk '{print $1}')
          echo "SHA_LINUX_ARM64: ${SHA_LINUX_ARM64}"
          
          # Linux x86_64
          URL="https://github.com/neptaco/${FORMULA_NAME}/releases/download/${VERSION}/${FORMULA_NAME}-${VERSION_NUM}-x86_64-unknown-linux-gnu.tar.gz"
          echo "Fetching SHA256 for Linux x86_64 from: ${URL}.sha256"
          SHA_LINUX_X64=$(curl -sL "${URL}.sha256" | awk '{print $1}')
          echo "SHA_LINUX_X64: ${SHA_LINUX_X64}"
          
          # Update the formula file
          FORMULA_FILE="Formula/${FORMULA_NAME}.rb"
          echo "Updating formula file: $FORMULA_FILE"
          
          # Check if file exists and is writable
          if [ ! -f "$FORMULA_FILE" ]; then
            echo "Error: Formula file not found: $FORMULA_FILE"
            exit 1
          fi
          
          if [ ! -w "$FORMULA_FILE" ]; then
            echo "Error: Formula file is not writable: $FORMULA_FILE"
            exit 1
          fi
          
          # Create backup
          cp "$FORMULA_FILE" "${FORMULA_FILE}.backup"
          echo "Created backup: ${FORMULA_FILE}.backup"
          
          # Update version
          echo "Updating version to: $VERSION_NUM"
          awk -v version="$VERSION_NUM" '{gsub(/version "[^"]*"/, "version \"" version "\""); print}' "$FORMULA_FILE" > "${FORMULA_FILE}.tmp" && mv "${FORMULA_FILE}.tmp" "$FORMULA_FILE" || {
            echo "Error: Failed to update version"
            exit 1
          }
          
          # Update SHA256 hashes
          echo "Updating SHA256 hashes..."
          
          # macOS ARM64
          echo "Updating macOS ARM64 SHA256: $SHA_MACOS_ARM64"
          awk -v sha="$SHA_MACOS_ARM64" '{gsub(/sha256 arm64_apple: "[^"]*"/, "sha256 arm64_apple: \"" sha "\""); print}' "$FORMULA_FILE" > "${FORMULA_FILE}.tmp" && mv "${FORMULA_FILE}.tmp" "$FORMULA_FILE" || {
            echo "Error: Failed to update macOS ARM64 SHA256"
            exit 1
          }
          
          # macOS x86_64
          echo "Updating macOS x86_64 SHA256: $SHA_MACOS_X64"
          awk -v sha="$SHA_MACOS_X64" '{gsub(/sha256 x86_64_apple: "[^"]*"/, "sha256 x86_64_apple: \"" sha "\""); print}' "$FORMULA_FILE" > "${FORMULA_FILE}.tmp" && mv "${FORMULA_FILE}.tmp" "$FORMULA_FILE" || {
            echo "Error: Failed to update macOS x86_64 SHA256"
            exit 1
          }
          
          # Linux ARM64
          echo "Updating Linux ARM64 SHA256: $SHA_LINUX_ARM64"
          awk -v sha="$SHA_LINUX_ARM64" '{gsub(/sha256 arm64_linux: "[^"]*"/, "sha256 arm64_linux: \"" sha "\""); print}' "$FORMULA_FILE" > "${FORMULA_FILE}.tmp" && mv "${FORMULA_FILE}.tmp" "$FORMULA_FILE" || {
            echo "Error: Failed to update Linux ARM64 SHA256"
            exit 1
          }
          
          # Linux x86_64
          echo "Updating Linux x86_64 SHA256: $SHA_LINUX_X64"
          awk -v sha="$SHA_LINUX_X64" '{gsub(/sha256 x86_64_linux: "[^"]*"/, "sha256 x86_64_linux: \"" sha "\""); print}' "$FORMULA_FILE" > "${FORMULA_FILE}.tmp" && mv "${FORMULA_FILE}.tmp" "$FORMULA_FILE" || {
            echo "Error: Failed to update Linux x86_64 SHA256"
            exit 1
          }
          
          echo "Formula file updated successfully"
          
          # Display changes
          echo "Formula updated:"
          git diff --color=always

      - name: Commit and Push
        run: |
          set -e
          
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          FORMULA_NAME=${{ github.event.client_payload.formula || github.event.inputs.formula }}
          VERSION=${{ github.event.client_payload.version || github.event.inputs.version }}
          
          git add Formula/${FORMULA_NAME}.rb
          
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update ${FORMULA_NAME} to ${VERSION}"
            git push
          fi